package HasherApp;


/**
* HasherApp/Hasher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hasher.idl
* Friday, 19 March, 2021 2:39:38 PM IST
*/

public interface Hasher extends HasherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hasher
