package HasherApp;


/**
* HasherApp/HasherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hasher.idl
* Friday, 19 March, 2021 2:39:38 PM IST
*/

public interface HasherOperations 
{
  String hashTheString (String data);
} // interface HasherOperations
