package HasherApp;

/**
* HasherApp/HasherHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hasher.idl
* Friday, 19 March, 2021 2:39:38 PM IST
*/

public final class HasherHolder implements org.omg.CORBA.portable.Streamable
{
  public HasherApp.Hasher value = null;

  public HasherHolder ()
  {
  }

  public HasherHolder (HasherApp.Hasher initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HasherApp.HasherHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HasherApp.HasherHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HasherApp.HasherHelper.type ();
  }

}
